export const BASE_URL = "http://localhost:4000"
export const LIST_PRODUCTS = "list-products"
export const MILKS = "foodtype/milk"
export const FROZENS = "foodtype/frozen"
export const CANDIES = "foodtype/candy"
export const BAKERIES = "foodtype/bakery"
export const CAKES = "foodtype/cake"
export const CANS = "foodtype/can"
export const CEREALS = "foodtype/cereal"

